# Generated by Django 4.0.5 on 2022-06-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('startdate', models.CharField(blank=True, db_column='startDate', max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('loadaddress', models.CharField(blank=True, db_column='loadAddress', max_length=30, null=True)),
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'convenience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('loadaddress', models.CharField(blank=True, db_column='loadAddress', max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('startdate', models.CharField(blank=True, db_column='startDate', max_length=30, null=True)),
                ('totaldoctor', models.IntegerField(blank=True, db_column='totalDoctor', null=True)),
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('name', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('loadaddress', models.CharField(blank=True, db_column='loadAddress', max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('startdate', models.CharField(blank=True, db_column='startDate', max_length=30, null=True)),
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacylocation',
            fields=[
                ('loadaddress', models.CharField(blank=True, db_column='loadAddress', max_length=30, null=True)),
                ('hospitalcount', models.IntegerField(blank=True, db_column='hospitalCount', null=True)),
                ('doctorcount', models.IntegerField(blank=True, db_column='doctorCount', null=True)),
                ('pharmacycount', models.IntegerField(blank=True, db_column='pharmacyCount', null=True)),
                ('dong', models.CharField(blank=True, max_length=11, null=True)),
                ('conveniencecount', models.IntegerField(blank=True, db_column='convenienceCount', null=True)),
                ('hospitalperpharmacy', models.FloatField(blank=True, db_column='hospitalPerPharmacy', null=True)),
                ('doctorperpharmacy', models.FloatField(blank=True, db_column='doctorPerPharmacy', null=True)),
                ('convenienceperpharmacy', models.FloatField(blank=True, db_column='conveniencePerPharmacy', null=True)),
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('viewcount', models.IntegerField(blank=True, db_column='viewCount', null=True)),
            ],
            options={
                'db_table': 'pharmacylocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('dong', models.CharField(blank=True, max_length=11, null=True)),
                ('name', models.CharField(blank=True, max_length=11, null=True)),
                ('line', models.CharField(blank=True, max_length=11, null=True)),
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
    ]
